# 22
# version
# CodeDeploy 버전을 이야기한다
# 프로젝트 버전이 아니므로 0.0 외에 다른 버전을 사용하면 오류가 발생한다.
# source
# CodeDeploy에서 전달해 준 파일 중 destination으로 이동시킬 대상을 지정
# 루트 경로(/)를 지정하면 전체 파일을 이야기한다.
# destination
# source에서 지정된 파일을 받을 위치이다.
# 이후 jar를 실행하는 등은 destination에서 옮긴 파일들로 진행된다.
# overwrite
# 기존에 파일들이 있으면 덮어쓸지를 결정한다.
# 현재 yes라고 했으니 파일들을 덮어쓰게 된다.
# ####
version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/step3/zip/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: stop.sh # 엔진엑스와 연결되어 있지 않은 스프링 부트를 종료함
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: start.sh # 엔진엑스와 연결되어 있지 않은 Port로 새 버전의 스프링부트를 시작
      timeout: 60
      runas: ec2-user
  ValidateService:
    - location: health.sh # 새 스프링부트가 정상적으로 실행됐는지 확인
      timeout: 60
      runas: ec2-user
